#!/bin/sh

java -jar yuicompressor-2.4.2.jar --type js  -o js/jquery.prettyPhoto.min.js js/jquery.prettyPhoto.js 
java -jar yuicompressor-2.4.2.jar --type js  -o js/klogger.min.js js/klogger.js 
java -jar yuicompressor-2.4.2.jar --type css -o css/prettyPhoto.min.css css/prettyPhoto.css
java -jar yuicompressor-2.4.2.jar --type css -o css/style.min.css css/style.css

